# Generated by Django 3.2.6 on 2022-06-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210620_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='miki.png', upload_to=''),
        ),
    ]
